### ISSUE TITLE
[Feature Request] Change password

### ISSUE THREAD

**Issue by marian-vladut** [tov101/Issues_forPlayers#1]
Would be nice to have available the possibility to change the password for the account.

![image](https://github.com/user-attachments/assets/c21f4ab1-21e1-4d16-b119-b929b55d0fb9)

**Comment by tov101** [comment]
Please check if it works and if everything is ok, then close this issue.

 - Forgotten password can be reset via: https://www.4players.ro/accounts/password_reset/
 - Password ca be changed via https://www.4players.ro/accounts/password_change/

![image](https://github.com/user-attachments/assets/735885f5-abeb-4e67-9538-82d649d8eb32)

**Comment by tov101** [comment]
Please re-open if needed.
